export interface GalleryItem {
  src: string;
  alt: string;
  category: string;
  width: number;
  height: number;
}

export const galleryItems: GalleryItem[] = [
  // ===== INTERIOR PAINTING =====
  {
    src: "/images/interior-painting-bathroom.jpg",
    alt: "Freshly painted bathroom with clean blue-gray walls",
    category: "Interior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/interior-painting-hallway.jpg",
    alt: "White hallway interior after professional painting",
    category: "Interior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/interior-painting-room-tealrug.jpg",
    alt: "Freshly painted living room with teal rug accent",
    category: "Interior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/interior-painting-stairwell-beforeafter.jpg",
    alt: "Stairwell before and after interior painting",
    category: "Interior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/interior-painting-vaultedceiling.jpg",
    alt: "Interior painting on vaulted ceiling in Ohio home",
    category: "Interior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/interior-painting-collage-bathroom.jpg",
    alt: "Bathroom painting project collage showing multiple angles",
    category: "Interior Painting",
    width: 1920,
    height: 3413,
  },
  {
    src: "/images/interior-painting-collage-fireplace.jpg",
    alt: "Fireplace area painting project collage",
    category: "Interior Painting",
    width: 1920,
    height: 3413,
  },
  {
    src: "/images/interior-painting-collage-fullhouse.jpg",
    alt: "Full house interior painting project collage",
    category: "Interior Painting",
    width: 1920,
    height: 3413,
  },
  {
    src: "/images/interior-painting-collage-kitchen.jpg",
    alt: "Kitchen painting project collage with before and after views",
    category: "Interior Painting",
    width: 1920,
    height: 3413,
  },
  {
    src: "/images/interior-painting-collage-multiroom.jpg",
    alt: "Multi-room interior painting project collage",
    category: "Interior Painting",
    width: 1920,
    height: 3413,
  },
  {
    src: "/images/interior-painting-collage-wholehouse2.jpg",
    alt: "Whole house interior painting project collage",
    category: "Interior Painting",
    width: 1920,
    height: 3413,
  },
  {
    src: "/images/gallery-interior-1.jpg",
    alt: "Interior painting project in Central Ohio home",
    category: "Interior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-interior-2.jpg",
    alt: "Professional interior wall painting with clean edges",
    category: "Interior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-interior-3.jpg",
    alt: "Freshly painted interior room in Fairfield County",
    category: "Interior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-interior-4.jpg",
    alt: "Interior painting with trim work detail",
    category: "Interior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-interior-5.jpg",
    alt: "Bedroom interior painting with accent wall",
    category: "Interior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-interior-6.jpg",
    alt: "Living area interior painting in Ohio home",
    category: "Interior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-interior-7.jpg",
    alt: "Interior hallway and doorway painting project",
    category: "Interior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-interior-8.jpg",
    alt: "Interior room painting with modern color palette",
    category: "Interior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-interior-9.jpg",
    alt: "Residential interior painting project",
    category: "Interior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-interior-10.jpg",
    alt: "Kitchen area interior painting with cabinet detail",
    category: "Interior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-interior-11.jpg",
    alt: "Interior painting project in newer Central Ohio home",
    category: "Interior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-interior-12.jpg",
    alt: "Interior bathroom painting with fresh coat",
    category: "Interior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-interior-13.jpg",
    alt: "Dining room interior painting with neutral tones",
    category: "Interior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-interior-14.jpg",
    alt: "Interior painting project with ceiling and wall detail",
    category: "Interior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-interior-15.jpg",
    alt: "Whole room interior painting with baseboard trim",
    category: "Interior Painting",
    width: 1920,
    height: 2560,
  },

  // ===== EXTERIOR PAINTING =====
  {
    src: "/images/exterior-painting-black-garage.jpg",
    alt: "Garage exterior painted black with clean finish",
    category: "Exterior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/exterior-painting-blue-porch.jpg",
    alt: "Exterior painting with blue accent porch in Ohio",
    category: "Exterior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/exterior-painting-brick-historic.jpg",
    alt: "Historic brick home exterior painting project",
    category: "Exterior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/exterior-painting-collage-garage.jpg",
    alt: "Garage exterior painting project collage",
    category: "Exterior Painting",
    width: 1920,
    height: 3413,
  },
  {
    src: "/images/exterior-painting-collage-house.jpg",
    alt: "House exterior painting project collage with multiple views",
    category: "Exterior Painting",
    width: 1920,
    height: 3413,
  },
  {
    src: "/images/exterior-painting-collage-winter.jpg",
    alt: "Winter exterior painting project collage",
    category: "Exterior Painting",
    width: 1920,
    height: 3413,
  },
  {
    src: "/images/fence-painting-gray.jpg",
    alt: "Gray fence painting along property line",
    category: "Exterior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/house-painting-brick-landscaped.jpg",
    alt: "Brick home exterior painting with landscaped yard",
    category: "Exterior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/house-painting-ranch.jpg",
    alt: "Ranch-style home exterior painting project",
    category: "Exterior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/house-painting-twostory.jpg",
    alt: "Two-story home exterior painting in Central Ohio",
    category: "Exterior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-exterior-1.jpg",
    alt: "Exterior painting on residential home",
    category: "Exterior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-exterior-2.jpg",
    alt: "Home exterior after professional painting",
    category: "Exterior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-exterior-3.jpg",
    alt: "Exterior siding painting project in Ohio",
    category: "Exterior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-exterior-4.jpg",
    alt: "Freshly painted home exterior with trim detail",
    category: "Exterior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-exterior-5.jpg",
    alt: "Exterior house painting with porch and shutters",
    category: "Exterior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-exterior-6.jpg",
    alt: "Professional exterior painting on Ohio home",
    category: "Exterior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-exterior-7.jpg",
    alt: "Exterior painting project with accent colors",
    category: "Exterior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-exterior-8.jpg",
    alt: "Home exterior painting with garage and trim",
    category: "Exterior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-exterior-9.jpg",
    alt: "Residential exterior painting in Central Ohio",
    category: "Exterior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-exterior-10.jpg",
    alt: "Exterior painting with new color scheme",
    category: "Exterior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-exterior-11.jpg",
    alt: "Exterior siding and trim painting project",
    category: "Exterior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-exterior-12.jpg",
    alt: "Complete home exterior painting makeover",
    category: "Exterior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-exterior-13.jpg",
    alt: "Exterior painting on two-tone home in Ohio",
    category: "Exterior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-exterior-14.jpg",
    alt: "House exterior painting with landscaping",
    category: "Exterior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-exterior-15.jpg",
    alt: "Exterior home painting with fresh curb appeal",
    category: "Exterior Painting",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-exterior-16.jpg",
    alt: "Professional exterior painting completed project",
    category: "Exterior Painting",
    width: 1920,
    height: 2560,
  },

  // ===== POWER WASHING =====
  {
    src: "/images/power-washing-action.jpg",
    alt: "Power washing vinyl siding on Ohio home",
    category: "Power Washing",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-powerwash-1.jpg",
    alt: "Power washing project on residential driveway",
    category: "Power Washing",
    width: 1920,
    height: 2560,
  },
  {
    src: "/images/gallery-powerwash-2.jpg",
    alt: "Power washing results on home exterior",
    category: "Power Washing",
    width: 1920,
    height: 2560,
  },

  // ===== DRYWALL REPAIR =====
  {
    src: "/images/drywall-repair-collage.jpg",
    alt: "Drywall repair project collage showing process and results",
    category: "Drywall Repair",
    width: 1920,
    height: 3413,
  },

  // ===== WOOD STAINING =====
  {
    src: "/images/wood-staining-garage.jpg",
    alt: "Wood staining on garage exterior in Fairfield County",
    category: "Wood Staining",
    width: 1920,
    height: 2560,
  },

  // ===== RESIDENTIAL EXTERIOR (April 2026) =====
  {
    src: "/images/exterior-painting-collage-ranch-doors.jpg",
    alt: "Ranch-style home exterior repaint with freshly painted garage door and side entry",
    category: "Exterior Painting",
    width: 1080,
    height: 1920,
  },
  {
    src: "/images/exterior-painting-collage-screened-porch.jpg",
    alt: "Screened porch painting project with refreshed ceiling, floor, trim, and ceiling fan",
    category: "Exterior Painting",
    width: 1080,
    height: 1920,
  },

  // ===== COMMERCIAL PAINTING =====
  {
    src: "/images/commercial-painting-steaknshake-front.jpg",
    alt: "Steak 'n Shake commercial exterior repaint — front entrance with new white finish and black accent stripe",
    category: "Commercial Painting",
    width: 1920,
    height: 1440,
  },
  {
    src: "/images/commercial-painting-steaknshake-drivethru.jpg",
    alt: "Steak 'n Shake commercial exterior repaint — drive-thru side wall after fresh coat",
    category: "Commercial Painting",
    width: 1920,
    height: 1440,
  },
  {
    src: "/images/commercial-painting-steaknshake-side.jpg",
    alt: "Steak 'n Shake commercial exterior repaint — side elevation with crisp white walls and black trim band",
    category: "Commercial Painting",
    width: 1920,
    height: 1440,
  },
  {
    src: "/images/exterior-painting-collage-condo-fence.jpg",
    alt: "Greensview Village condominium exterior painting — wrought iron fencing and community signage",
    category: "Commercial Painting",
    width: 1080,
    height: 1920,
  },
];

export const galleryCategories = [
  "All",
  ...Array.from(new Set(galleryItems.map((item) => item.category))),
];
